logging:
  level:
    root: INFO
    org.springframework: ERROR
    com.pocopay.transaction: DEBUG

spring:
  application:
    name: ms-transaction
  datasource:
    url: jdbc:postgresql://localhost:5432/transaction_db
    username: postgres
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:liquibase/changelog-master.yaml
  rabbitmq:
    virtual-host: /
    host: localhost
    port: 5672
    username: admin
    password: admin
    queue:
      transaction: transaction
server:
  port: 2020